server:
  port: ${port:8092}
spring:
  application:
    name: cooperative-vote-system
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        publishExchangeAssemblyResult:
          destination: publish-exchange-assembly-result
      rabbit:
        bindings:
          publishExchangeAssemblyResult:
            producer:
              exchangeType: fanout
      binders:
        rabbitMQ: 
          type: rabbit
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_schema: CooperativeDataBase
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CooperativeDataBase?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: 123456  
service:
  urls:
    herokuapp: https://user-info.herokuapp.com/users/